/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieticket;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jitender
 */
public class selectseats2 extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public selectseats2() {
        initComponents();
        bookedticket();
    }
     ResultSet rs;
     PreparedStatement pk;
     ArrayList  movieTicket=new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tgl_A1 = new javax.swing.JToggleButton();
        tgl_A3 = new javax.swing.JToggleButton();
        tgl_A4 = new javax.swing.JToggleButton();
        tgl_A5 = new javax.swing.JToggleButton();
        tgl_A6 = new javax.swing.JToggleButton();
        tgl_A7 = new javax.swing.JToggleButton();
        tgl_A2 = new javax.swing.JToggleButton();
        tgl_A9 = new javax.swing.JToggleButton();
        tgl_A8 = new javax.swing.JToggleButton();
        tgl_B3 = new javax.swing.JToggleButton();
        tgl_B4 = new javax.swing.JToggleButton();
        tgl_B5 = new javax.swing.JToggleButton();
        tgl_B6 = new javax.swing.JToggleButton();
        tgl_B7 = new javax.swing.JToggleButton();
        tgl_B2 = new javax.swing.JToggleButton();
        tgl_B9 = new javax.swing.JToggleButton();
        tgl_B8 = new javax.swing.JToggleButton();
        tgl_B1 = new javax.swing.JToggleButton();
        tgl_C3 = new javax.swing.JToggleButton();
        tgl_C4 = new javax.swing.JToggleButton();
        tgl_C5 = new javax.swing.JToggleButton();
        tgl_C6 = new javax.swing.JToggleButton();
        tgl_C7 = new javax.swing.JToggleButton();
        tgl_C2 = new javax.swing.JToggleButton();
        tgl_C9 = new javax.swing.JToggleButton();
        tgl_C8 = new javax.swing.JToggleButton();
        tgl_C1 = new javax.swing.JToggleButton();
        tgl_D3 = new javax.swing.JToggleButton();
        tgl_D4 = new javax.swing.JToggleButton();
        tgl_D5 = new javax.swing.JToggleButton();
        tgl_D6 = new javax.swing.JToggleButton();
        tgl_D7 = new javax.swing.JToggleButton();
        tgl_D2 = new javax.swing.JToggleButton();
        tgl_D9 = new javax.swing.JToggleButton();
        tgl_D8 = new javax.swing.JToggleButton();
        tgl_D1 = new javax.swing.JToggleButton();
        tgl_E3 = new javax.swing.JToggleButton();
        tgl_E4 = new javax.swing.JToggleButton();
        tgl_E5 = new javax.swing.JToggleButton();
        tgl_E6 = new javax.swing.JToggleButton();
        tgl_E7 = new javax.swing.JToggleButton();
        tgl_E2 = new javax.swing.JToggleButton();
        tgl_E9 = new javax.swing.JToggleButton();
        tgl_E8 = new javax.swing.JToggleButton();
        tgl_E1 = new javax.swing.JToggleButton();
        btn_Book = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tgl_A1.setText("A1");
        tgl_A1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tgl_A1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tgl_A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_A1ActionPerformed(evt);
            }
        });

        tgl_A3.setText("A3");
        tgl_A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_A3ActionPerformed(evt);
            }
        });

        tgl_A4.setText("A4");
        tgl_A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_A4ActionPerformed(evt);
            }
        });

        tgl_A5.setText("A5");
        tgl_A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_A5ActionPerformed(evt);
            }
        });

        tgl_A6.setText("A6");
        tgl_A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_A6ActionPerformed(evt);
            }
        });

        tgl_A7.setText("A7");
        tgl_A7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_A7ActionPerformed(evt);
            }
        });

        tgl_A2.setText("A2");
        tgl_A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_A2ActionPerformed(evt);
            }
        });

        tgl_A9.setText("A9");
        tgl_A9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_A9ActionPerformed(evt);
            }
        });

        tgl_A8.setText("A8");
        tgl_A8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_A8ActionPerformed(evt);
            }
        });

        tgl_B3.setText("B3");
        tgl_B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_B3ActionPerformed(evt);
            }
        });

        tgl_B4.setText("B4");
        tgl_B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_B4ActionPerformed(evt);
            }
        });

        tgl_B5.setText("B5");
        tgl_B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_B5ActionPerformed(evt);
            }
        });

        tgl_B6.setText("B6");
        tgl_B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_B6ActionPerformed(evt);
            }
        });

        tgl_B7.setText("B7");
        tgl_B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_B7ActionPerformed(evt);
            }
        });

        tgl_B2.setText("B2");
        tgl_B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_B2ActionPerformed(evt);
            }
        });

        tgl_B9.setText("B9");
        tgl_B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_B9ActionPerformed(evt);
            }
        });

        tgl_B8.setText("B8");
        tgl_B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_B8ActionPerformed(evt);
            }
        });

        tgl_B1.setText("B1");
        tgl_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_B1ActionPerformed(evt);
            }
        });

        tgl_C3.setText("C3");
        tgl_C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_C3ActionPerformed(evt);
            }
        });

        tgl_C4.setText("C4");
        tgl_C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_C4ActionPerformed(evt);
            }
        });

        tgl_C5.setText("C5");
        tgl_C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_C5ActionPerformed(evt);
            }
        });

        tgl_C6.setText("C6");
        tgl_C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_C6ActionPerformed(evt);
            }
        });

        tgl_C7.setText("C7");
        tgl_C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_C7ActionPerformed(evt);
            }
        });

        tgl_C2.setText("C2");
        tgl_C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_C2ActionPerformed(evt);
            }
        });

        tgl_C9.setText("C9");
        tgl_C9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_C9ActionPerformed(evt);
            }
        });

        tgl_C8.setText("C8");
        tgl_C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_C8ActionPerformed(evt);
            }
        });

        tgl_C1.setText("C1");
        tgl_C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_C1ActionPerformed(evt);
            }
        });

        tgl_D3.setText("D3");
        tgl_D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_D3ActionPerformed(evt);
            }
        });

        tgl_D4.setText("D4");
        tgl_D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_D4ActionPerformed(evt);
            }
        });

        tgl_D5.setText("D5");
        tgl_D5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_D5ActionPerformed(evt);
            }
        });

        tgl_D6.setText("D6");
        tgl_D6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_D6ActionPerformed(evt);
            }
        });

        tgl_D7.setText("D7");
        tgl_D7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_D7ActionPerformed(evt);
            }
        });

        tgl_D2.setText("D2");
        tgl_D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_D2ActionPerformed(evt);
            }
        });

        tgl_D9.setText("D9");
        tgl_D9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_D9ActionPerformed(evt);
            }
        });

        tgl_D8.setText("D8");
        tgl_D8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_D8ActionPerformed(evt);
            }
        });

        tgl_D1.setText("D1");
        tgl_D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_D1ActionPerformed(evt);
            }
        });

        tgl_E3.setText("E3");
        tgl_E3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_E3ActionPerformed(evt);
            }
        });

        tgl_E4.setText("E4");
        tgl_E4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_E4ActionPerformed(evt);
            }
        });

        tgl_E5.setText("E5");
        tgl_E5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_E5ActionPerformed(evt);
            }
        });

        tgl_E6.setText("E6");
        tgl_E6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_E6ActionPerformed(evt);
            }
        });

        tgl_E7.setText("E7");
        tgl_E7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_E7ActionPerformed(evt);
            }
        });

        tgl_E2.setText("E2");
        tgl_E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_E2ActionPerformed(evt);
            }
        });

        tgl_E9.setText("E9");
        tgl_E9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_E9ActionPerformed(evt);
            }
        });

        tgl_E8.setText("E8");
        tgl_E8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_E8ActionPerformed(evt);
            }
        });

        tgl_E1.setText("E1");
        tgl_E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_E1ActionPerformed(evt);
            }
        });

        btn_Book.setBackground(new java.awt.Color(153, 153, 153));
        btn_Book.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_Book.setForeground(new java.awt.Color(102, 102, 255));
        btn_Book.setText("Book Tickets");
        btn_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BookActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("MovieTicket.com");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage (7).jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Book)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tgl_A1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_A2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_A3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_A4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_A5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)
                                        .addComponent(tgl_A6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_A7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_A8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_A9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tgl_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_D2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_D3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_D4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_D5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)
                                        .addComponent(tgl_D6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_D7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_D8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_D9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tgl_E1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_E2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_E3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_E4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_E5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)
                                        .addComponent(tgl_E6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_E7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_E8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_E9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tgl_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_B2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_B3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tgl_B4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tgl_B5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)
                                        .addComponent(tgl_B6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_B7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_B8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_B9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tgl_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_C3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_C4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_C5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)
                                        .addComponent(tgl_C6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_C7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_C8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tgl_C9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tgl_A2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_A3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_A4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_A5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_A6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_A7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_A8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_A9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tgl_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_B2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_B3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_B5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_B6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_B7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_B8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_B9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_B4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tgl_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_C3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_C4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_C5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_C6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_C7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_C8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_C9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tgl_A1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tgl_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_D2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_D3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_D4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_D5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_D6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_D7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_D8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_D9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tgl_E1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_E2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_E3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_E4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_E5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_E6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_E7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_E8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_E9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(btn_Book)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tgl_A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_A1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_A1ActionPerformed

    private void tgl_A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_A3ActionPerformed

    private void tgl_A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_A4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_A4ActionPerformed

    private void tgl_A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_A5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_A5ActionPerformed

    private void tgl_A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_A6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_A6ActionPerformed

    private void tgl_A7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_A7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_A7ActionPerformed

    private void tgl_A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_A2ActionPerformed

    private void tgl_A9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_A9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_A9ActionPerformed

    private void tgl_A8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_A8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_A8ActionPerformed

    private void tgl_B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_B3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_B3ActionPerformed

    private void tgl_B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_B4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_B4ActionPerformed

    private void tgl_B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_B5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_B5ActionPerformed

    private void tgl_B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_B6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_B6ActionPerformed

    private void tgl_B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_B7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_B7ActionPerformed

    private void tgl_B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_B2ActionPerformed

    private void tgl_B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_B9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_B9ActionPerformed

    private void tgl_B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_B8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_B8ActionPerformed

    private void tgl_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_B1ActionPerformed

    private void tgl_C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_C3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_C3ActionPerformed

    private void tgl_C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_C4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_C4ActionPerformed

    private void tgl_C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_C5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_C5ActionPerformed

    private void tgl_C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_C6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_C6ActionPerformed

    private void tgl_C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_C7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_C7ActionPerformed

    private void tgl_C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_C2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_C2ActionPerformed

    private void tgl_C9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_C9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_C9ActionPerformed

    private void tgl_C8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_C8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_C8ActionPerformed

    private void tgl_C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_C1ActionPerformed

    private void tgl_D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_D3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_D3ActionPerformed

    private void tgl_D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_D4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_D4ActionPerformed

    private void tgl_D5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_D5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_D5ActionPerformed

    private void tgl_D6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_D6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_D6ActionPerformed

    private void tgl_D7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_D7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_D7ActionPerformed

    private void tgl_D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_D2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_D2ActionPerformed

    private void tgl_D9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_D9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_D9ActionPerformed

    private void tgl_D8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_D8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_D8ActionPerformed

    private void tgl_D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_D1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_D1ActionPerformed

    private void tgl_E3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_E3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_E3ActionPerformed

    private void tgl_E4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_E4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_E4ActionPerformed

    private void tgl_E5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_E5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_E5ActionPerformed

    private void tgl_E6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_E6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_E6ActionPerformed

    private void tgl_E7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_E7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_E7ActionPerformed

    private void tgl_E2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_E2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_E2ActionPerformed

    private void tgl_E9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_E9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_E9ActionPerformed

    private void tgl_E8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_E8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_E8ActionPerformed

    private void tgl_E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_E1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_E1ActionPerformed

    private void btn_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BookActionPerformed
        // TODO add your handling code here:

        if (tgl_A1.isSelected()) {
            movieTicket.add(tgl_A1.getText());
        }

        if (tgl_A2.isSelected()) {
            movieTicket.add(tgl_A2.getText());
        }

        if (tgl_A3.isSelected()) {
            movieTicket.add(tgl_A3.getText());
        }

        if (tgl_A4.isSelected()) {
            movieTicket.add(tgl_A4.getText());
        }

        if (tgl_A5.isSelected()) {
            movieTicket.add(tgl_A5.getText());
        }

        if (tgl_A6.isSelected()) {
            movieTicket.add(tgl_A6.getText());
        }
        if (tgl_A7.isSelected()) {
            movieTicket.add(tgl_A7.getText());
        }
        if (tgl_A8.isSelected()) {
            movieTicket.add(tgl_A8.getText());
        }
        if (tgl_A9.isSelected()) {
            movieTicket.add(tgl_A9.getText());
        }
        if (tgl_B1.isSelected()) {
            movieTicket.add(tgl_B1.getText());
        }
        if (tgl_B2.isSelected()) {
            movieTicket.add(tgl_B2.getText());
        }
        if (tgl_B3.isSelected()) {
            movieTicket.add(tgl_B3.getText());
        }
        if (tgl_B4.isSelected()) {
            movieTicket.add(tgl_B4.getText());
        }
        if (tgl_B5.isSelected()) {
            movieTicket.add(tgl_B5.getText());
        }
        if (tgl_B6.isSelected()) {
            movieTicket.add(tgl_B6.getText());
        }
        if (tgl_B7.isSelected()) {
            movieTicket.add(tgl_B7.getText());
        }
        if (tgl_B8.isSelected()) {
            movieTicket.add(tgl_B8.getText());
        }
        if (tgl_B9.isSelected()) {
            movieTicket.add(tgl_B9.getText());
        }
        if (tgl_C1.isSelected()) {
            movieTicket.add(tgl_C1.getText());
        }
        if (tgl_C2.isSelected()) {
            movieTicket.add(tgl_C2.getText());
        }
        if (tgl_C3.isSelected()) {
            movieTicket.add(tgl_C3.getText());
        }
        if (tgl_C4.isSelected()) {
            movieTicket.add(tgl_C4.getText());
        }
        if (tgl_C5.isSelected()) {
            movieTicket.add(tgl_C5.getText());
        }

        if (tgl_C6.isSelected()) {
            movieTicket.add(tgl_C6.getText());
        }
        if (tgl_C7.isSelected()) {
            movieTicket.add(tgl_C7.getText());
        }
        if (tgl_C8.isSelected()) {
            movieTicket.add(tgl_C8.getText());
        }
        if (tgl_C9.isSelected()) {
            movieTicket.add(tgl_C9.getText());
        }

        if (tgl_D1.isSelected()) {
            movieTicket.add(tgl_D1.getText());
        }

        if (tgl_D2.isSelected()) {
            movieTicket.add(tgl_D2.getText());
        }

        if (tgl_D3.isSelected()) {
            movieTicket.add(tgl_D3.getText());
        }

        if (tgl_D4.isSelected()) {
            movieTicket.add(tgl_D4.getText());
        }

        if (tgl_D5.isSelected()) {
            movieTicket.add(tgl_D5.getText());
        }

        if (tgl_D6.isSelected()) {
            movieTicket.add(tgl_D6.getText());
        }
        if (tgl_D7.isSelected()) {
            movieTicket.add(tgl_D7.getText());
        }
        if (tgl_D8.isSelected()) {
            movieTicket.add(tgl_D8.getText());
        }
        if (tgl_D9.isSelected()) {
            movieTicket.add(tgl_D9.getText());
        }

        if (tgl_E1.isSelected()) {
            movieTicket.add(tgl_E1.getText());
        }

        if (tgl_E2.isSelected()) {
            movieTicket.add(tgl_E2.getText());
        }

        if (tgl_E3.isSelected()) {
            movieTicket.add(tgl_E3.getText());
        }

        if (tgl_E4.isSelected()) {
            movieTicket.add(tgl_E4.getText());
        }

        if (tgl_E5.isSelected()) {
            movieTicket.add(tgl_E5.getText());
        }

        if (tgl_E6.isSelected()) {
            movieTicket.add(tgl_E6.getText());
        }
        if (tgl_E7.isSelected()) {
            movieTicket.add(tgl_E7.getText());
        }
        if (tgl_E8.isSelected()) {
            movieTicket.add(tgl_E8.getText());
        }
        if (tgl_E9.isSelected()) {
            movieTicket.add(tgl_E9.getText());
        }

        String query="INSERT INTO `bookedticket2` values (?,?)";
        try {
           pk=Myconnection.getConnection().prepareStatement(query);
               String movie="Shadaa";
               pk.setString(1, movie);
            for(Object o:movieTicket){
                pk.setString(2, o.toString());
                pk.executeUpdate();
            }
            JOptionPane.showMessageDialog(rootPane,"Ticket booked");
        } catch (SQLException e) {
            System.out.println(e);
        }

        movieTicket.stream().map((o) -> o.toString()).forEachOrdered((ticketnum) -> {
            System.out.println("Selected ticket is " +ticketnum);
        });
        
       ticket tc=new ticket();
      tc.setVisible(true);
      this.setVisible(false);

    }//GEN-LAST:event_btn_BookActionPerformed

    public final  void bookedticket(){
        String query="Select `tickets` from `bookedticket2`";  
        ArrayList ticket=new ArrayList();
        try {
            pk=Myconnection.getConnection().prepareStatement(query);
            rs=pk.executeQuery();
             while (rs.next()) {
                ticket.add(rs.getString(1));
            }
             
             System.out.println(ticket);
                        
             for(Object o:ticket){
                 
                String ticketnum=o.toString();
                 if (tgl_A1.getText().equals(o)) {
                     tgl_A1.setEnabled(false);
                 }
                  if (tgl_A2.getText().equals(o)) {
                      tgl_A2.setEnabled(false);
                 }
                  if (tgl_A3.getText().equals(o)) {
                      tgl_A3.setEnabled(false);
                 }
                  if (tgl_A4.getText().equals(o)) {
                      tgl_A4.setEnabled(false);
                 }
                  if (tgl_A5.getText().equals(o)) {
                      tgl_A5.setEnabled(false);
                  }
                   if (tgl_A6.getText().equals(o)) {
                       tgl_A6.setEnabled(false);
                 }
                  if (tgl_A7.getText().equals(o)) {
                      tgl_A7.setEnabled(false);
                 }
                  if (tgl_A8.getText().equals(o)) {
                      tgl_A8.setEnabled(false);
                 }
                  if (tgl_A9.getText().equals(o)) {
                      tgl_A9.setEnabled(false);
                 }
                 
                 if (tgl_B1.getText().equals(o)) {
                     tgl_B1.setEnabled(false);
                 }
                  if (tgl_B2.getText().equals(o)) {
                      tgl_B2.setEnabled(false);
                 }
                  if (tgl_B3.getText().equals(o)) {
                      tgl_B3.setEnabled(false);
                 }
                  if (tgl_B4.getText().equals(o)) {
                      tgl_B4.setEnabled(false);
                 }
                  if (tgl_B5.getText().equals(o)) {
                      tgl_B5.setEnabled(false);
                  }
                   if (tgl_B6.getText().equals(o)) {
                       tgl_B6.setEnabled(false);
                 }
                  if (tgl_B7.getText().equals(o)) {
                      tgl_B7.setEnabled(false);
                 }
                  if (tgl_B8.getText().equals(o)) {
                      tgl_B8.setEnabled(false);
                 }
                  if (tgl_B9.getText().equals(o)) {
                      tgl_B9.setEnabled(false);
                 }
                  
                 if (tgl_C1.getText().equals(o)) {
                     tgl_C1.setEnabled(false);
                 }
                  if (tgl_C2.getText().equals(o)) {
                      tgl_C2.setEnabled(false);
                 }
                  if (tgl_C3.getText().equals(o)) {
                      tgl_C3.setEnabled(false);
                 }
                  if (tgl_C4.getText().equals(o)) {
                      tgl_C4.setEnabled(false);
                 }
                  if (tgl_C5.getText().equals(o)) {
                      tgl_C5.setEnabled(false);
                  }
                   if (tgl_C6.getText().equals(o)) {
                       tgl_C6.setEnabled(false);
                 }
                  if (tgl_C7.getText().equals(o)) {
                      tgl_C7.setEnabled(false);
                 }
                  if (tgl_C8.getText().equals(o)) {
                      tgl_C8.setEnabled(false);
                 }
                  if (tgl_C9.getText().equals(o)) {
                      tgl_C9.setEnabled(false);
                 }
                  
                 if (tgl_D1.getText().equals(o)) {
                     tgl_D1.setEnabled(false);
                 }
                  if (tgl_D2.getText().equals(o)) {
                      tgl_D2.setEnabled(false);
                 }
                  if (tgl_D3.getText().equals(o)) {
                      tgl_D3.setEnabled(false);
                 }
                  if (tgl_D4.getText().equals(o)) {
                      tgl_D4.setEnabled(false);
                 }
                  if (tgl_D5.getText().equals(o)) {
                      tgl_D5.setEnabled(false);
                  }
                   if (tgl_D6.getText().equals(o)) {
                       tgl_D6.setEnabled(false);
                 }
                  if (tgl_D7.getText().equals(o)) {
                      tgl_D7.setEnabled(false);
                 }
                  if (tgl_D8.getText().equals(o)) {
                      tgl_D8.setEnabled(false);
                 }
                  if (tgl_D9.getText().equals(o)) {
                      tgl_D9.setEnabled(false);
                 }
                  
                 if (tgl_E1.getText().equals(o)) {
                     tgl_E1.setEnabled(false);
                 }
                  if (tgl_E2.getText().equals(o)) {
                      tgl_E2.setEnabled(false);
                 }
                  if (tgl_E3.getText().equals(o)) {
                      tgl_E3.setEnabled(false);
                 }
                  if (tgl_E4.getText().equals(o)) {
                      tgl_E4.setEnabled(false);
                 }
                  if (tgl_E5.getText().equals(o)) {
                      tgl_E5.setEnabled(false);
                  }
                   if (tgl_E6.getText().equals(o)) {
                       tgl_E6.setEnabled(false);
                 }
                  if (tgl_E7.getText().equals(o)) {
                      tgl_E7.setEnabled(false);
                 }
                  if (tgl_E8.getText().equals(o)) {
                      tgl_E8.setEnabled(false);
                 }
                  if (tgl_E9.getText().equals(o)) {
                      tgl_E9.setEnabled(false);
                 } 
           }        
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectseats2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new selectseats2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Book;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton tgl_A1;
    private javax.swing.JToggleButton tgl_A2;
    private javax.swing.JToggleButton tgl_A3;
    private javax.swing.JToggleButton tgl_A4;
    private javax.swing.JToggleButton tgl_A5;
    private javax.swing.JToggleButton tgl_A6;
    private javax.swing.JToggleButton tgl_A7;
    private javax.swing.JToggleButton tgl_A8;
    private javax.swing.JToggleButton tgl_A9;
    private javax.swing.JToggleButton tgl_B1;
    private javax.swing.JToggleButton tgl_B2;
    private javax.swing.JToggleButton tgl_B3;
    private javax.swing.JToggleButton tgl_B4;
    private javax.swing.JToggleButton tgl_B5;
    private javax.swing.JToggleButton tgl_B6;
    private javax.swing.JToggleButton tgl_B7;
    private javax.swing.JToggleButton tgl_B8;
    private javax.swing.JToggleButton tgl_B9;
    private javax.swing.JToggleButton tgl_C1;
    private javax.swing.JToggleButton tgl_C2;
    private javax.swing.JToggleButton tgl_C3;
    private javax.swing.JToggleButton tgl_C4;
    private javax.swing.JToggleButton tgl_C5;
    private javax.swing.JToggleButton tgl_C6;
    private javax.swing.JToggleButton tgl_C7;
    private javax.swing.JToggleButton tgl_C8;
    private javax.swing.JToggleButton tgl_C9;
    private javax.swing.JToggleButton tgl_D1;
    private javax.swing.JToggleButton tgl_D2;
    private javax.swing.JToggleButton tgl_D3;
    private javax.swing.JToggleButton tgl_D4;
    private javax.swing.JToggleButton tgl_D5;
    private javax.swing.JToggleButton tgl_D6;
    private javax.swing.JToggleButton tgl_D7;
    private javax.swing.JToggleButton tgl_D8;
    private javax.swing.JToggleButton tgl_D9;
    private javax.swing.JToggleButton tgl_E1;
    private javax.swing.JToggleButton tgl_E2;
    private javax.swing.JToggleButton tgl_E3;
    private javax.swing.JToggleButton tgl_E4;
    private javax.swing.JToggleButton tgl_E5;
    private javax.swing.JToggleButton tgl_E6;
    private javax.swing.JToggleButton tgl_E7;
    private javax.swing.JToggleButton tgl_E8;
    private javax.swing.JToggleButton tgl_E9;
    // End of variables declaration//GEN-END:variables
}
