/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieticket;

/**
 *
 * @author Jitender
 */
public class Selectmovie extends javax.swing.JFrame {

    /**
     * Creates new form Selectmovie
     */
    public Selectmovie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                lbl_kabirsingh = new javax.swing.JLabel();
                lbl_spiderman = new javax.swing.JLabel();
                lbl_spiderman1 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                btn_booktckt1 = new javax.swing.JButton();
                btn_booktckt2 = new javax.swing.JButton();
                btn_booktckt3 = new javax.swing.JButton();

                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jScrollPane1.setViewportView(jTextArea1);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                lbl_kabirsingh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage (6).jpg"))); // NOI18N
                lbl_kabirsingh.setMaximumSize(new java.awt.Dimension(250, 250));
                lbl_kabirsingh.setMinimumSize(new java.awt.Dimension(250, 250));
                lbl_kabirsingh.setPreferredSize(new java.awt.Dimension(250, 250));
                lbl_kabirsingh.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbl_kabirsinghMouseClicked(evt);
                        }
                });

                lbl_spiderman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Spiderman.jpg"))); // NOI18N
                lbl_spiderman.setMaximumSize(new java.awt.Dimension(250, 250));
                lbl_spiderman.setMinimumSize(new java.awt.Dimension(250, 250));
                lbl_spiderman.setPreferredSize(new java.awt.Dimension(250, 250));
                lbl_spiderman.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbl_spidermanMouseClicked(evt);
                        }
                });

                lbl_spiderman1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage (7).jpg"))); // NOI18N
                lbl_spiderman1.setMaximumSize(new java.awt.Dimension(250, 250));
                lbl_spiderman1.setMinimumSize(new java.awt.Dimension(250, 250));
                lbl_spiderman1.setPreferredSize(new java.awt.Dimension(250, 250));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon.jpg"))); // NOI18N

                jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 100)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(153, 153, 255));
                jLabel2.setText("MovieTicket.com");

                btn_booktckt1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
                btn_booktckt1.setForeground(new java.awt.Color(51, 51, 255));
                btn_booktckt1.setText("Book Ticket");
                btn_booktckt1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_booktckt1ActionPerformed(evt);
                        }
                });

                btn_booktckt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
                btn_booktckt2.setForeground(new java.awt.Color(51, 51, 255));
                btn_booktckt2.setText("Book Ticket");
                btn_booktckt2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_booktckt2ActionPerformed(evt);
                        }
                });

                btn_booktckt3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
                btn_booktckt3.setForeground(new java.awt.Color(51, 51, 255));
                btn_booktckt3.setText("Book Ticket");
                btn_booktckt3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_booktckt3ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_spiderman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbl_kabirsingh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(46, 46, 46)
                                                .addComponent(lbl_spiderman1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(59, 59, 59))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2)
                                                .addContainerGap(35, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(btn_booktckt1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_booktckt2)
                                .addGap(175, 175, 175)
                                .addComponent(btn_booktckt3)
                                .addGap(107, 107, 107))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbl_spiderman1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbl_kabirsingh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbl_spiderman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_booktckt1)
                                        .addComponent(btn_booktckt2)
                                        .addComponent(btn_booktckt3))
                                .addContainerGap(51, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void lbl_spidermanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_spidermanMouseClicked
    }//GEN-LAST:event_lbl_spidermanMouseClicked
    private void lbl_kabirsinghMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_kabirsinghMouseClicked
    }//GEN-LAST:event_lbl_kabirsinghMouseClicked

    private void btn_booktckt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_booktckt2ActionPerformed
       
        selectseats1 sl=new selectseats1();
        sl.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_booktckt2ActionPerformed

    private void btn_booktckt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_booktckt1ActionPerformed
      
        selectseats sl=new selectseats();
        sl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_booktckt1ActionPerformed

    private void btn_booktckt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_booktckt3ActionPerformed
         
        selectseats2 sl=new selectseats2();
        sl.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_booktckt3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selectmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selectmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selectmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selectmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Selectmovie().setVisible(true);
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btn_booktckt1;
        private javax.swing.JButton btn_booktckt2;
        private javax.swing.JButton btn_booktckt3;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JLabel lbl_kabirsingh;
        private javax.swing.JLabel lbl_spiderman;
        private javax.swing.JLabel lbl_spiderman1;
        // End of variables declaration//GEN-END:variables
}
